test:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: ${dir}/audio
  transcription_dir: ${dir}/transcriptions
  instance_transforms: ${transforms.instance_transforms.inference}
  text_encoder: ${text_encoder}
