train:
  x: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        params_path: normalization_params.json
        device: ${trainer.device}
inference:
  x: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        params_path: normalization_params.json
        device: ${trainer.device}
        